$(document).ready(function(){
    $("#mycarousel").carousel({interval:2000});
    $("#carouselButton").click(function(){
        if($("#carouselButton").children('span').hasClass("fa-pause")){
            $("#mycarousel").carousel('pause');
            $("#carouselButton").children('span').removeClass("fa-pause");
            $("#carouselButton").children('span').addClass("fa-play");
            $("#carouselButton").removeClass("btn-danger");
            $("#carouselButton").addClass("btn-success");
        }
        else if($("#carouselButton").children('span').hasClass("fa-play")){
            $("#mycarousel").carousel('cycle');
            $("#carouselButton").children('span').removeClass("fa-play");
            $("#carouselButton").children('span').addClass("fa-pause");
            $("#carouselButton").removeClass("btn-success");
            $("#carouselButton").addClass("btn-danger");
        }
    });

    $("#loginbutton").click(function(){
        $("#loginModal").modal("show");
    });
    $("#buttonclose").click(function(){
        $("#loginModal").modal("hide");
    });
    $("#buttoncancelclose").click(function(){
        $("#loginModal").modal("hide");
    });
    $("#reservebutton").click(function(){
        $("#reservemodal").modal("show");
    });
    $("#buttonclose1").click(function(){
        $("#reservemodal").modal("hide");
    });
    $("#buttoncancelclose1").click(function(){
        $("#reservemodal").modal("hide");
    });
});